export const identity = {
  name: "Nyaradzo Bere",
  preferredName: "Naya",
  pronouns: "she/her",
  initials: "NB",
  location: "Los Angeles, CA",
  role: "Developer Relations · LLM Engineer · Technical Content Creator",
  brand: "@TheBlackFemaleEngineer",
  communitySize: "250,000+",
  email: "NayaUnityBere@gmail.com",
  partnershipsEmail: "naya@bfepartnerships.com",
  github: "https://github.com/nayaunity",
  linkedin: "https://linkedin.com/in/theblackfemaleengineer",
  tiktok: "https://www.tiktok.com/@theblackfemaleengineer",
  instagram: "https://instagram.com/theblackfemaleengineer",
  youtube: "https://youtube.com/@theblackfemaleengineer",
  medium: "https://medium.com/@theblackfemaleengineer",
  calendar: "mailto:NayaUnityBere@gmail.com?subject=Let%27s%20chat",
};
